export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const OAUTH_OK = 'OAUTH_OK';
export const OAUTH_BAD_REQUEST = 'OAUTH_BAD_REQUEST';

export const CENTER_CONTAINER_CONTENT = 'CENTER_CONTAINER_CONTENT';

export const PROFILE_INFO_START = 'PROFILE_INFO_START';
export const PROFILE_INFO_SUCCESS = 'PROFILE_INFO_SUCCESS';
export const PROFILE_INFO_FAIL = 'PROFILE_INFO_FAIL';

export const PROFILE_BOOKS_START = 'PROFILE_BOOKS_START';
export const PROFILE_BOOKS_SUCCESS = 'PROFILE_BOOKS_SUCCESS';
export const PROFILE_BOOKS_FAIL = 'PROFILE_BOOKS_FAIL';


export const POST_IMAGE_START = 'POST_IMAGE_START';
export const POST_IMAGE_SUCCESS = 'POST_IMAGE_SUCCESS';
export const POST_IMAGE_FAIL = 'POST_IMAGE_FAIL';

export const GET_IMAGE_START = 'GET_IMAGE_START';
export const GET_IMAGE_SUCCESS = 'GET_IMAGE_SUCCESS';
export const GET_IMAGE_FAIL = 'GET_IMAGE_FAIL';